#ifndef GLOBALDEF_H
#define GLOBALDEF_H

/*#define DEBUG true
#ifdef DEBUG
#include <QDebug>
#include <QTest>
#endif*/

#define PI 3.14159265
enum DrawMethod{LEVEL, CYCLE, FINDPATHS, M4};
//enum IDTYPE{ID, INID, CARD};
enum ROLE{G, B};
enum VIEW_MODE{VIEW, SELECT, MOVE, DRAG, DEL};//模式有浏览，选择，移动，拖拽，删除
enum RELATION_GUOUP{MONEY_R, ID_R, DEV_R, SOCIETYR_R, ADDR_R ,IP_R, MOBILE_R, MAC_R, ATM_R};//关系栏
enum NODE_ATTRIBUTE_GROUP{HIDE_PATH_A, TOP_COLOR_A, NAME_A, ID_A, CUSTOMER_NO_A, LEVEL_A, MOBILE_A, LINKER_NUM_A, EMAIL_A, BANK_ADDR_A , CARD_NO_A, OTHER_BANK_A, THIRD_PART_A};//结点属性
//enum ANALYSE_GROUP{};
enum ATTRNAME{MONEY, ID, DEV, SOCIETYR,TOPCOLORBOX, NAMEBOX, IDBOX, CUSTOMERNOBOX, LEVELBOX, LINEBOX, LINKERNUMBOX, EMAILBOX, MOBILEBOX,CARDNO,ADDRESSBOX};





#endif // GLOBALDEF_H
